const state={jobs:[],token:sessionStorage.getItem("secscanApiToken")||"",poll:null};
const $=(id)=>document.getElementById(id);
function headers(json=false){const h={};if(json)h["Content-Type"]="application/json";if(state.token)h.Authorization=`Bearer ${state.token}`;return h}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}});if(response.status===401){showTokenDialog();throw new Error("API authentication required")};if(!response.ok){let detail=`Request failed (${response.status})`;try{const body=await response.json();detail=body.detail||detail}catch{}throw new Error(detail)};const type=response.headers.get("content-type")||"";return type.includes("application/json")?response.json():response.text()}
function flash(message,error=false){const node=$("flash");node.textContent=message;node.classList.toggle("error",error);node.classList.remove("hidden");setTimeout(()=>node.classList.add("hidden"),4500)}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===name));document.querySelectorAll(".nav-item").forEach(v=>v.classList.toggle("active",v.dataset.view===name));const titles={dashboard:"Dashboard","new-scan":"New scan",scans:"Scans","job-detail":"Scan details"};$("page-title").textContent=titles[name]||"secscan"}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function formatDate(value){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString()}
function scanTable(jobs){if(!jobs.length)return'<div class="empty">No scans yet. Run your first scan to get started.</div>';return `<div style="overflow:auto"><table class="scan-table"><thead><tr><th>Target</th><th>Scanner</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${jobs.map(job=>`<tr><td class="target-cell" title="${escapeHtml(job.target)}">${escapeHtml(job.target)}</td><td>${escapeHtml(job.scanner)}</td><td><span class="status ${escapeHtml(job.status)}">${escapeHtml(job.status)}</span></td><td>${escapeHtml(formatDate(job.created_at))}</td><td><a class="row-link" data-job-id="${escapeHtml(job.id)}">View</a></td></tr>`).join("")}</tbody></table></div>`}
function bindJobLinks(root=document){root.querySelectorAll("[data-job-id]").forEach(link=>link.addEventListener("click",()=>openJob(link.dataset.jobId)))}
function renderJobs(){const counts={queued:0,running:0,completed:0,failed:0};state.jobs.forEach(j=>{if(counts[j.status]!==undefined)counts[j.status]++});Object.entries(counts).forEach(([key,value])=>$( `metric-${key}`).textContent=value);$("recent-scans").innerHTML=scanTable(state.jobs.slice(0,8));$("all-scans").innerHTML=scanTable(state.jobs);bindJobLinks($("recent-scans"));bindJobLinks($("all-scans"))}
async function loadJobs(){try{state.jobs=await api("/api/v1/jobs?limit=100");renderJobs()}catch(error){flash(error.message,true)}}
async function health(){try{const response=await fetch("/healthz");if(!response.ok)throw new Error();const body=await response.json();if(body.status!=="ok")throw new Error();$("health-dot").className="health-dot ok";$("health-label").textContent="Scanner online"}catch{$("health-dot").className="health-dot bad";$("health-label").textContent="Scanner unavailable"}}
function severityCounts(report){const counts={CRITICAL:0,HIGH:0,MEDIUM:0,LOW:0,UNKNOWN:0};const findings=Array.isArray(report.findings)?report.findings:[];findings.forEach(f=>{const severity=String(f.severity||"UNKNOWN").toUpperCase();counts[severity]=(counts[severity]||0)+1});return counts}
async function openJob(id){showView("job-detail");$("job-content").innerHTML='<div class="panel"><div class="empty">Loading scan…</div></div>';try{const job=await api(`/api/v1/jobs/${id}`);let manifest=null,report=null;try{manifest=await api(`/api/v1/jobs/${id}/artifacts`)}catch{}try{report=await api(`/api/v1/jobs/${id}/artifacts/secscan.json`)}catch{}const counts=severityCounts(report||{});const artifacts=manifest?.artifacts||[];const artifactHtml=artifacts.length?artifacts.map(a=>`<a class="artifact-link" href="/api/v1/jobs/${encodeURIComponent(id)}/artifacts/${encodeURIComponent(a.name)}" data-artifact="${escapeHtml(a.name)}">${escapeHtml(a.name)}</a>`).join(""):'<span class="muted">No artifacts available yet.</span>';$("job-content").innerHTML=`<div class="detail-grid"><div class="detail-card"><span>Status</span><strong><span class="status ${escapeHtml(job.status)}">${escapeHtml(job.status)}</span></strong></div><div class="detail-card"><span>Scanner</span><strong>${escapeHtml(job.scanner)}</strong></div><div class="detail-card"><span>Exit code</span><strong>${job.exit_code??"—"}</strong></div><div class="detail-card"><span>Created</span><strong>${escapeHtml(formatDate(job.created_at))}</strong></div></div><div class="panel"><div class="panel-heading"><div><p class="eyebrow">Target</p><h2>${escapeHtml(job.target)}</h2></div></div>${job.error?`<div class="flash error">${escapeHtml(job.error)}</div>`:""}<div class="severity-grid">${Object.entries(counts).map(([severity,count])=>`<div class="severity"><strong>${count}</strong><span>${severity}</span></div>`).join("")}</div><h3>Artifacts</h3><div class="artifact-list">${artifactHtml}</div></div>`;document.querySelectorAll("[data-artifact]").forEach(link=>link.addEventListener("click",event=>{if(!state.token)return;event.preventDefault();downloadArtifact(link.href,link.dataset.artifact)}))}catch(error){$("job-content").innerHTML=`<div class="panel"><div class="flash error">${escapeHtml(error.message)}</div></div>`}}
async function downloadArtifact(url,name){try{const response=await fetch(url,{headers:headers()});if(!response.ok)throw new Error(`Unable to download ${name}`);const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement("a");a.href=objectUrl;a.download=name;a.click();URL.revokeObjectURL(objectUrl)}catch(error){flash(error.message,true)}}
function showTokenDialog(){ $("api-token").value=state.token;$("token-dialog").showModal() }
document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));document.querySelectorAll("[data-view-target]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.viewTarget)));
$("api-token-button").addEventListener("click",showTokenDialog);$("save-token").addEventListener("click",()=>{state.token=$("api-token").value.trim();if(state.token)sessionStorage.setItem("secscanApiToken",state.token);else sessionStorage.removeItem("secscanApiToken");setTimeout(loadJobs,0)});$("refresh-scans").addEventListener("click",loadJobs);$("back-to-scans").addEventListener("click",()=>showView("scans"));
$("scanner").addEventListener("change",event=>{const examples={image:"alpine:3.20",filesystem:"/workspace",repository:"/workspace",sbom:"/workspace/build.cdx.json"};$("target").placeholder=examples[event.target.value]});
$("scan-form").addEventListener("submit",async event=>{event.preventDefault();const payload={scanner:$("scanner").value,target:$("target").value.trim(),timeout:Number($("timeout").value)};if($("fail-on").value)payload.fail_on=$("fail-on").value;if($("policy").value.trim())payload.policy=$("policy").value.trim();if($("baseline").value.trim())payload.baseline=$("baseline").value.trim();try{const job=await api("/api/v1/jobs",{method:"POST",body:JSON.stringify(payload)});flash("Scan queued successfully.");event.target.reset();$("timeout").value="600";await loadJobs();openJob(job.id)}catch(error){flash(error.message,true)}});
async function tick(){await health();await loadJobs()}tick();state.poll=setInterval(loadJobs,5000);
