const state={jobs:[],token:sessionStorage.getItem("secscanApiToken")||"",poll:null,detailPoll:null,detailJobId:null};
const $=(id)=>document.getElementById(id);
function headers(json=false){const h={};if(json)h["Content-Type"]="application/json";if(state.token)h.Authorization=`Bearer ${state.token}`;return h}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers(Boolean(options.body)),...(options.headers||{})}});if(response.status===401){showTokenDialog();throw new Error("API authentication required")};if(!response.ok){let detail=`Request failed (${response.status})`;try{const body=await response.json();detail=body.detail||detail}catch{}throw new Error(detail)};const type=response.headers.get("content-type")||"";return type.includes("application/json")?response.json():response.text()}
function flash(message,error=false){const node=$("flash");node.textContent=message;node.classList.toggle("error",error);node.classList.remove("hidden");setTimeout(()=>node.classList.add("hidden"),4500)}
function stopDetailPolling(){if(state.detailPoll){clearTimeout(state.detailPoll);state.detailPoll=null}state.detailJobId=null}
function showView(name){if(name!=="job-detail")stopDetailPolling();document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===name));document.querySelectorAll(".nav-item").forEach(v=>v.classList.toggle("active",v.dataset.view===name));const titles={dashboard:"Dashboard","new-scan":"New scan",scans:"Scans","job-detail":"Scan details"};$("page-title").textContent=titles[name]||"secscan"}
function escapeHtml(value){return String(value??"").replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"}[c]))}
function formatDate(value){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString()}
function scanTable(jobs){if(!jobs.length)return'<div class="empty">No scans yet. Run your first scan to get started.</div>';return `<div style="overflow:auto"><table class="scan-table"><thead><tr><th>Target</th><th>Scanner</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${jobs.map(job=>`<tr><td class="target-cell" title="${escapeHtml(job.target)}">${escapeHtml(job.target)}</td><td>${escapeHtml(job.scanner)}</td><td><span class="status ${escapeHtml(job.status)}">${escapeHtml(job.status)}</span></td><td>${escapeHtml(formatDate(job.created_at))}</td><td><a class="row-link" data-job-id="${escapeHtml(job.id)}">View</a></td></tr>`).join("")}</tbody></table></div>`}
function bindJobLinks(root=document){root.querySelectorAll("[data-job-id]").forEach(link=>link.addEventListener("click",()=>openJob(link.dataset.jobId)))}
function renderJobs(){const counts={queued:0,running:0,completed:0,failed:0};state.jobs.forEach(j=>{if(counts[j.status]!==undefined)counts[j.status]++});Object.entries(counts).forEach(([key,value])=>$( `metric-${key}`).textContent=value);$("recent-scans").innerHTML=scanTable(state.jobs.slice(0,8));$("all-scans").innerHTML=scanTable(state.jobs);bindJobLinks($("recent-scans"));bindJobLinks($("all-scans"))}
async function loadJobs(){try{state.jobs=await api("/api/v1/jobs?limit=100");renderJobs()}catch(error){flash(error.message,true)}}
async function health(){try{const response=await fetch("/healthz");if(!response.ok)throw new Error();const body=await response.json();if(body.status!=="ok")throw new Error();$("health-dot").className="health-dot ok";$("health-label").textContent="Scanner online"}catch{$("health-dot").className="health-dot bad";$("health-label").textContent="Scanner unavailable"}}
function severityCounts(report){const counts={CRITICAL:0,HIGH:0,MEDIUM:0,LOW:0,UNKNOWN:0};const findings=Array.isArray(report.findings)?report.findings:[];findings.forEach(f=>{const severity=String(f.severity||"UNKNOWN").toUpperCase();counts[severity]=(counts[severity]||0)+1});return counts}
function severityBadge(severity){const value=String(severity||"UNKNOWN").toUpperCase();return `<span class="severity-badge severity-${escapeHtml(value.toLowerCase())}">${escapeHtml(value)}</span>`}
function findingRows(findings){if(!findings.length)return'<tr><td colspan="7" class="empty-cell">No findings match these filters.</td></tr>';return findings.map(f=>{const advisory=f.primary_url?`<a href="${escapeHtml(f.primary_url)}" target="_blank" rel="noreferrer">${escapeHtml(f.vulnerability_id)}</a>`:escapeHtml(f.vulnerability_id);return `<tr><td>${severityBadge(f.severity)}</td><td>${advisory}</td><td><strong>${escapeHtml(f.package_name)}</strong><small>${escapeHtml(f.package_type||"")}</small></td><td>${escapeHtml(f.installed_version||"—")}</td><td>${escapeHtml(f.fixed_version||"No fix listed")}</td><td class="finding-title">${escapeHtml(f.title||"—")}</td><td class="target-cell" title="${escapeHtml(f.target||"")}">${escapeHtml(f.target||"—")}</td></tr>`}).join("")}
function findingsPanel(findings){return `<div class="panel findings-panel"><div class="panel-heading"><div><p class="eyebrow">Vulnerabilities</p><h2>Findings <span class="count-pill" id="finding-count">${findings.length}</span></h2></div></div><div class="finding-controls"><input id="finding-search" type="search" placeholder="Search CVE, package, title, or target"><select id="finding-severity"><option value="">All severities</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option><option>UNKNOWN</option></select><select id="finding-fix"><option value="">All fix states</option><option value="available">Fix available</option><option value="none">No fix listed</option></select></div><div class="finding-table-wrap"><table class="finding-table"><thead><tr><th>Severity</th><th>Vulnerability</th><th>Package</th><th>Installed</th><th>Fixed</th><th>Title</th><th>Target</th></tr></thead><tbody id="finding-rows">${findingRows(findings)}</tbody></table></div></div>`}
function bindFindingFilters(findings){const search=$("finding-search"),severity=$("finding-severity"),fix=$("finding-fix"),rows=$("finding-rows"),count=$("finding-count");if(!search||!severity||!fix||!rows||!count)return;const render=()=>{const query=search.value.trim().toLowerCase();const selectedSeverity=severity.value;const fixState=fix.value;const filtered=findings.filter(f=>{const text=[f.vulnerability_id,f.package_name,f.title,f.target,f.installed_version,f.fixed_version].join(" ").toLowerCase();const severityMatch=!selectedSeverity||String(f.severity||"UNKNOWN").toUpperCase()===selectedSeverity;const fixMatch=!fixState||(fixState==="available"?Boolean(f.fixed_version):!f.fixed_version);return (!query||text.includes(query))&&severityMatch&&fixMatch});rows.innerHTML=findingRows(filtered);count.textContent=filtered.length};[search,severity,fix].forEach(control=>control.addEventListener(control.tagName==="INPUT"?"input":"change",render))}
function diffPanel(diff){if(!diff||!diff.summary)return"";const summary=diff.summary;const groups=[["new","New findings"],["resolved","Resolved findings"],["unchanged","Unchanged findings"]];return `<div class="panel"><div class="panel-heading"><div><p class="eyebrow">Baseline comparison</p><h2>What changed</h2></div></div><div class="diff-grid"><div class="diff-card new"><strong>${Number(summary.new||0)}</strong><span>New</span></div><div class="diff-card resolved"><strong>${Number(summary.resolved||0)}</strong><span>Resolved</span></div><div class="diff-card unchanged"><strong>${Number(summary.unchanged||0)}</strong><span>Unchanged</span></div></div>${groups.map(([key,label])=>{const items=Array.isArray(diff[key])?diff[key]:[];if(!items.length)return"";return `<details class="diff-group" ${key==="new"?"open":""}><summary>${label} (${items.length})</summary><div class="compact-findings">${items.slice(0,100).map(f=>`<div><span>${severityBadge(f.severity)}</span><strong>${escapeHtml(f.vulnerability_id)}</strong><span>${escapeHtml(f.package_name)}</span><span>${escapeHtml(f.fixed_version?`fix ${f.fixed_version}`:"no fix listed")}</span></div>`).join("")}${items.length>100?`<p class="muted">Showing first 100 of ${items.length}.</p>`:""}</div></details>`}).join("")}</div>`}
function scheduleDetailRefresh(id,status){if(!["queued","running"].includes(status)){stopDetailPolling();return}state.detailJobId=id;state.detailPoll=setTimeout(()=>{if(state.detailJobId===id&&$("job-detail").classList.contains("active"))openJob(id,true)},2000)}
async function openJob(id,refresh=false){if(!refresh){stopDetailPolling();showView("job-detail");$("job-content").innerHTML='<div class="panel"><div class="empty">Loading scan…</div></div>'}try{const job=await api(`/api/v1/jobs/${id}`);if(refresh&&state.detailJobId!==id)return;let manifest=null,report=null,diff=null;try{manifest=await api(`/api/v1/jobs/${id}/artifacts`)}catch{}try{report=await api(`/api/v1/jobs/${id}/artifacts/secscan.json`)}catch{}try{diff=await api(`/api/v1/jobs/${id}/artifacts/secscan.diff.json`)}catch{}const counts=severityCounts(report||{});const findings=Array.isArray(report?.findings)?report.findings:[];const artifacts=manifest?.artifacts||[];const artifactHtml=artifacts.length?artifacts.map(a=>`<a class="artifact-link" href="/api/v1/jobs/${encodeURIComponent(id)}/artifacts/${encodeURIComponent(a.name)}" data-artifact="${escapeHtml(a.name)}">${escapeHtml(a.name)}</a>`).join(""):'<span class="muted">No artifacts available yet.</span>';$("job-content").innerHTML=`<div class="detail-grid"><div class="detail-card"><span>Status</span><strong><span class="status ${escapeHtml(job.status)}">${escapeHtml(job.status)}</span></strong></div><div class="detail-card"><span>Scanner</span><strong>${escapeHtml(job.scanner)}</strong></div><div class="detail-card"><span>Exit code</span><strong>${job.exit_code??"—"}</strong></div><div class="detail-card"><span>Created</span><strong>${escapeHtml(formatDate(job.created_at))}</strong></div></div><div class="panel"><div class="panel-heading"><div><p class="eyebrow">Target</p><h2>${escapeHtml(job.target)}</h2></div></div>${job.error?`<div class="flash error">${escapeHtml(job.error)}</div>`:""}<div class="severity-grid">${Object.entries(counts).map(([severity,count])=>`<div class="severity severity-${escapeHtml(severity.toLowerCase())}"><strong>${count}</strong><span>${severity}</span></div>`).join("")}</div><h3>Artifacts</h3><div class="artifact-list">${artifactHtml}</div></div>${diffPanel(diff)}${report?findingsPanel(findings):""}`;document.querySelectorAll("[data-artifact]").forEach(link=>link.addEventListener("click",event=>{if(!state.token)return;event.preventDefault();downloadArtifact(link.href,link.dataset.artifact)}));bindFindingFilters(findings);scheduleDetailRefresh(id,job.status)}catch(error){stopDetailPolling();$("job-content").innerHTML=`<div class="panel"><div class="flash error">${escapeHtml(error.message)}</div></div>`}}
async function downloadArtifact(url,name){try{const response=await fetch(url,{headers:headers()});if(!response.ok)throw new Error(`Unable to download ${name}`);const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement("a");a.href=objectUrl;a.download=name;a.click();URL.revokeObjectURL(objectUrl)}catch(error){flash(error.message,true)}}
function showTokenDialog(){ $("api-token").value=state.token;$("token-dialog").showModal() }
document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));document.querySelectorAll("[data-view-target]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.viewTarget)));
$("api-token-button").addEventListener("click",showTokenDialog);$("save-token").addEventListener("click",()=>{state.token=$("api-token").value.trim();if(state.token)sessionStorage.setItem("secscanApiToken",state.token);else sessionStorage.removeItem("secscanApiToken");setTimeout(loadJobs,0)});$("refresh-scans").addEventListener("click",loadJobs);$("back-to-scans").addEventListener("click",()=>showView("scans"));
$("scanner").addEventListener("change",event=>{const examples={image:"alpine:3.20",filesystem:"/workspace",repository:"/workspace",sbom:"/workspace/build.cdx.json"};$("target").placeholder=examples[event.target.value]});
$("scan-form").addEventListener("submit",async event=>{event.preventDefault();const payload={scanner:$("scanner").value,target:$("target").value.trim(),timeout:Number($("timeout").value)};if($("fail-on").value)payload.fail_on=$("fail-on").value;if($("policy").value.trim())payload.policy=$("policy").value.trim();if($("baseline").value.trim())payload.baseline=$("baseline").value.trim();try{const job=await api("/api/v1/jobs",{method:"POST",body:JSON.stringify(payload)});flash("Scan queued successfully.");event.target.reset();$("timeout").value="600";await loadJobs();openJob(job.id)}catch(error){flash(error.message,true)}});
async function tick(){await health();await loadJobs()}tick();state.poll=setInterval(loadJobs,5000);
